INSERT INTO FACILITY(ID, FACILITYNAME, STATUS) VALUES(1, 'House','Available');
INSERT INTO FACILITY(ID, FACILITYNAME, STATUS) VALUES(2, 'Control Room', 'Available');
INSERT INTO FACILITY(ID, FACILITYNAME, STATUS) VALUES(3, 'Experimental Garden', 'Available');
